version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      # Reemplaza con el comando real para ejecutar tus pruebas
      - run:
          name: Run tests
          command: npx playwright test  # Aquí puedes usar el comando adecuado para tu proyecto

  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      # Reemplaza con los pasos reales para construir tu proyecto
      - run:
          name: Build an artifact
          command: touch example.txt

      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
