version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18  # Usar una imagen de Node.js que te ayude a instalar dependencias

    steps:
      - checkout  # Se asegura de que el código se haya descargado

      - run:
          name: Install dependencies
          command: npm install  # Instala las dependencias de Node.js

      - run:
          name: Run Playwright tests
          command: npx playwright test  # Ejecuta tus pruebas Playwright

  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
