version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.14
    steps:
    - setup_remote_docker:
      version: 20.10.7
      docker_layer_caching: true
    - run:
      name: Clean Docker cache
      command: docker builder prune --all -f 
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
