version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16
    steps:
      - setup_remote_docker:
          docker_layer_caching: true  # Habilitar el caching de las capas de Docker

      - checkout

      # Paso para instalar las dependencias
      - run:
          name: Install dependencies
          command: npm install

      # Ejecutar las pruebas de Playwright
      - run:
          name: Run Playwright tests
          command: npx playwright test


  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
